NNPEFWEB/Controllers/CPOUpdateController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using NNPEFWEB.Data;
using NNPEFWEB.Models;
using NNPEFWEB.Repository;
using NNPEFWEB.Service;
using NNPEFWEB.ViewModel;
using OfficeOpenXml;
using Wkhtmltopdf.NetCore;

namespace NNPEFWEB.Controllers
{
    public class CPOUpdateController : Controller
    {
        private readonly IPersonService personService;
        private readonly ISystemsInfoService _systemsInfoService;
        private readonly IPersonInfoService personinfoService;
        private readonly ApplicationDbContext _context;
        private readonly IUnitOfWorks unitOfWorks;
        private readonly IMapper imapper;
        private readonly IGeneratePdf _generatepdf;
        private readonly string connectionString;

        public CPOUpdateController(IConfiguration configuration, IGeneratePdf generatepdf, IMapper _imapper,
                                      IUnitOfWorks unitOfWorks, IPersonInfoService personinfoService, IPersonService personService, ApplicationDbContext _context,
                                      ISystemsInfoService systemsInfoService)
        {
            this._context = _context;
            this.personService = personService;
            this._systemsInfoService = systemsInfoService;
            this.personinfoService = personinfoService;
            this.unitOfWorks = unitOfWorks;
            imapper = _imapper;
            _generatepdf = generatepdf;
            connectionString = configuration.GetConnectionString("DefaultConnection");
        }
        public IActionResult sectiona()
        {
            return View();
        }
        public IActionResult sectionb()
        {
            return View();
        }
        public IActionResult sectionc()
        {
            return View();
        }
        public IActionResult sectiond()
        {
            return View();
        }
        public IActionResult sectione()
        {
            return View();
        }
        public IActionResult sectionf()
        {
            return View();
        }
        public ActionResult UpdatedPersonelByCPO(string ship)
        {
            ViewBag.ShipList = GetShip();
            var user = _context.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
            string shipname= ship;
            ViewData["shipSearchedID"] = shipname;
            //if (ship != null)
            //{
            //     shipname = _context.ef_ships.FirstOrDefault(x => x.Id == Convert.ToInt32(ship)).shipName;
            //     ViewData["shipSearchedID"] = shipname;
            //}
            var pp = personinfoService.GetUpdatedPersonnelByCpo(user.Appointment, shipname);
            return View(pp);
        }
        //public ActionResult UpdatedPayroll()
        //{
        //    return View();
        //}
        //[HttpPost]
        public ActionResult UpdatedPayroll(int id)
        {
            //string user = User.Identity.Name;
            var user = _context.Users.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
            try
            {
                using (SqlConnection sqlcon = new SqlConnection(connectionString))
                {

                    using (SqlCommand cmd = new SqlCommand("UpdatePayroll", sqlcon))
                    {
                        cmd.CommandTimeout = 1200;
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.Add(new SqlParameter("@id", id));
                        cmd.Parameters.Add(new SqlParameter("@username", user.UserName));



                        sqlcon.Open();
                        cmd.ExecuteNonQuery();
                        TempData["UpdateMessage"] = "Sucessfully Updated";
                    }
                }
            }
            catch (Exception ex)
            {

                TempData["UpdateMessage"] = "Updated Fail";
                //   ex.Message;
            }


            return RedirectToAction("UpdatedPersonelByCPO");
        }
    

       public string getsection(string appointment)
        {
            string sect="";
            if (appointment == "SectionA")
            {
                sect = "1";
            }
            else if (appointment == "SectionB")
            {
                sect = "2";
            }
            else if (appointment == "SectionC")
            {
                sect = "3";
            }
            else if (appointment == "SectionD")
            {
                sect = "4";
            }
            else if (appointment == "SectionE")
            {
                sect = "5";
            }
            else if (appointment == "SectionF")
            {
                sect = "5";
            }
            return sect;
        }
        public List<SelectListItem> GetShip()
        {
            var lgaList = (from rk in _context.ef_ships.OrderBy(x=>x.shipName)
                           select new SelectListItem()
                           {
                               Text = rk.shipName,
                               Value = rk.shipName,
                           }).ToList();

            lgaList.Insert(0, new SelectListItem()
            {
                Text = "All",
                Value = string.Empty
            });
            return lgaList;
        }
        public ActionResult UpdatedPersonel(int id)
        {
            string user = User.Identity.Name;
            try
            {
                using (SqlConnection sqlcon = new SqlConnection(connectionString))
                {

                    using (SqlCommand cmd = new SqlCommand("UpdatePayrollWithEF", sqlcon))
                    {
                        cmd.CommandTimeout = 1200;
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.Add(new SqlParameter("@personid", id));
                        cmd.Parameters.Add(new SqlParameter("@username", User.Identity.Name));


                        sqlcon.Open();
                        cmd.ExecuteNonQuery();
                        TempData["UpdateMessage"] = "Sucessfully Updated";
                    }
                }
            }
            catch (Exception ex)
            {

                TempData["UpdateMessage"] = "Updated Fail";
                //   ex.Message;
            }


            return RedirectToAction("UpdatedPersonelList");
         }
        public async Task<IActionResult> ListOfAllStaff(string reporttype, string shipToSearch,string payclass,string type, int? pageNumber)
        {
            try
            {
                if (reporttype == "All")
                    reporttype = null;
                ViewData["type"] = type;
                ViewData["reporttype"] = reporttype;
                ViewData["Payclass"] = payclass;
                ViewData["shipSearchedID"] = shipToSearch;
                var ppersons = await personinfoService.GetPersonnelStatusReport(reporttype, shipToSearch, payclass,pageNumber);

            var allShip = GetShip();

            //if (!string.IsNullOrEmpty(shipToSearch) && shipToSearch != "AllShip")
            //{
            //    //var shipSearched = _context.ef_ships.Where(x=>x.shipName==shipToSearch).FirstOrDefault();

            //    ViewData["shipSearchedID"] = shipToSearch;

            ////    allShip.Insert(0, new SelectListItem { Value = shipSearched.shipName, Text = shipSearched.shipName });
            ////    allShip.Insert(1, new SelectListItem { Value = "AllShip", Text = "All Ship" });
            //}
            //else
            //{
            //    ViewData["shipSearchedID"] = "AllShip";

            //  //  allShip.Insert(0, new SelectListItem { Value = "AllShip", Text = "All Ship" });
            //}

            ViewBag.ShipList = allShip;

            return View(ppersons);

            }
            catch (Exception ex)
            {
                TempData["UpdateMessage"] = "Updated Fail";

                throw;
            }
        }
        public Task<IActionResult> ListOfAllStaffReport(string ship, string shipToSearch,string payclass,string type)
        {

            var pp = personinfoService.GetPersonnelStatusRepoReport(ship, shipToSearch, payclass);
            List<RPTPersonModel> rpt = new List<RPTPersonModel>();
            foreach (var person in pp)
            {
                var pps = new RPTPersonModel
                {
                    ServiceNumber = person.serviceNumber,
                    Rank = person.Rank,
                    Name = person.Surname + " " + person.OtherName,
                    Ship = person.ship,
                    GSM_NO = person.gsm_number,
                    Date_Of_Birth = person.Birthdate == null ? "00-00-0000" : person.Birthdate.ToString(),
                    Residential_Address = person.home_address,
                    Date_Of_Expiration = person.expirationOfEngagementDate == null ? "00-00-0000" : person.expirationOfEngagementDate.ToString(),
                    Seniority_Date = person.seniorityDate == null ? "00-00-0000" : person.seniorityDate.ToString(),
                    Email_Address = person.email,
                    NOK = person.nok_name,
                    NOK_GSM_NO = person.nok_phone,
                    Bank = person.Bankcode,
                    Account_No = person.BankACNumber,
                    Accomodation_Status = person.AcommodationStatus,
                };
                rpt.Add(pps);
             }

            return _generatepdf.GetPdf("Reports/StaffReportList", rpt);
        }
        public Task<IActionResult> ListOfCompletedForm(string ship)
        {
            ViewBag.ShipList = GetShip();

NNPEFWEB/Views/CPOUpdate/ListOfAllStaff.cshtml
@model NNPEFWEB.ViewModel.PaginatedList<NNPEFWEB.Models.ef_personalInfo>
@using Microsoft.AspNetCore.Authorization

@{ ViewData["Title"] = "UpdatedPersonelByCPO"; }



<h1 style="margin-top:-20px">Personnel Report List</h1>
<br />
<h4>Filter By: </h4>
<div class="row">
    <div class="col-md-8 mb-4">
        <form asp-action="ListOfAllStaff" method="get" asp-controller="CPOUpdate">
            <div class="row">
                <div class="col-md-3">
                    <label class="control-label">Status</label>
                    <select name="reporttype" class="form-control">
                        @if (ViewData["reporttype"] != null)
                        {

                            @switch (ViewData["reporttype"])
                            {
                                @*case "AllStaff":
                        <option selected value="@ViewData["reporttype"]">All</option>
                        <option value="SHIP">Completed By Personnel</option>
                        <option value="CPO">Authenticated By Ship</option>
                        <option value="Verified">Certified HOD</option>
                        //<option value="Processed">Processed Form</option>
                        break;*@
                                case "Completed":
                                    <option>All</option>
                                    <option selected value="@ViewData["reporttype"]">Completed By Personnel</option>
                                    <option value="CPO">Authenticated By Ship</option>
                                    <option value="Verified">Certified HOD</option>
                                    // <option value="Processed">Processed Form</option>
                                    break;
                                case "Auth":
                                    <option>All</option>
                                    <option value="SHIP">Completed By Personnel</option>
                                    <option selected value="@ViewData["reporttype"]">Authenticated By Ship</option>
                                    <option value="Verified">Certified HOD</option>
                                    //<option value="Processed">Processed Form</option>
                                    break;
                                case "Verified":
                                    <option>All</option>
                                    <option value="SHIP">Completed By Personnel</option>
                                    <option value="CPO">Authenticated By Ship</option>
                                    <option selected value="@ViewData["reporttype"]">Certified HOD</option>
                                    //<option value="Processed">Processed Form</option>
                                    break;
                                @*case "Processed":
                        <option value="AllStaff">All</option>
                        <option value="SHIP">Completed Form</option>
                        <option value="CPO">Authenticated Form</option>
                        <option value="Verified">Certified Form</option>
                        <option selected value="@ViewData["reporttype"]">Processed Form</option>
                        break;*@
                                default:
                                    <option>All</option>
                                    <option value="SHIP">Completed By Personnel</option>
                                    <option value="CPO">Authenticated By Ship</option>
                                    <option value="Verified">Certified By HOD</option>
                                    //<option value="Processed">Processed Form</option>
                                    break;
                            }
                        }
                        else
                        {
                            <option>All</option>
                            <option value="SHIP">Completed By Persoonel</option>
                            <option value="CPO">Authenticated By Ship</option>
                            <option value="Verified">Certified By HOD</option>
                        }



                    </select>
                </div>

                <div class="col-md-3">
                    <label class="control-label">Ship</label>
                    <select name="shipToSearch"
                            class="form-control"
                            asp-items="@(new SelectList(ViewBag.ShipList,"Value", "Text"))">
                    </select>
                </div>
                <div class="col-md-2">
                    <label class="control-label">Pay Class</label>
                    <select name="payclass" class="form-control">
                        <option></option>
                        <option value="1">Officers</option>
                        <option value="2">W/Officers</option>
                        <option value="3">JRPA</option>
                        <option value="4">JRPB</option>
                        <option value="5">JRPC</option>
                        <option value="6">TRNP</option>
                    </select>
                </div>

                <div class="col-md-2">
                    <label class="control-label">Report Type</label>
                    <select class="form-control" name="type">
                        <option value="Paycard">To Open Paycard</option>
                        <option value="Payroll">To Update Payroll</option>
                    </select>
                </div>

                <div class="col-md-2" style="margin-top:30px">
                    <input type="submit" class="btn btn-primary" value="Filter" />
                </div>

            </div>
        </form>
    </div>
    <div class="col-md-2 mt-4">
        <form asp-action="Export" method="post" asp-controller="CPOUpdate">

            <input type="hidden" name="ship" value="@ViewData["reporttype"]" />
            <input type="hidden" name="type" value="@ViewData["type"]" />

            <input type="hidden" name="shipToSearch" value="@ViewData["shipSearchedID"]" />
            <input type="hidden" name="payclass" value="@ViewData["Payclass"]" />

            <div class="col-md-2">
                <input type="submit" class="btn btn-primary" value="Download To Excel" target="_blank"/>
            </div>
        </form>
    </div>

    <div class="col-md-2 mt-4">
        <form asp-action="ListOfAllStaffReport" method="get" asp-controller="CPOUpdate">

            <input type="hidden" name="ship" value="@ViewData["reporttype"]" />

            <input type="hidden" name="shipToSearch" value="@ViewData["shipSearchedID"]" />
            <input type="hidden" name="payclass" value="@ViewData["Payclass"]" />
            <input type="hidden" name="type" value="@ViewData["type"]" />

            <input type="submit" class="btn btn-primary" value="Download To PDF" target="_blank"/>
        </form>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Rank</th>
            <th>Service No</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Ship</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var r in Model)
        {
            <tr>
                <td>@r.Rank</td>
                <td>@r.serviceNumber</td>
                <td>@r.Surname</td>
                <td>@r.OtherName</td>
                <td>@r.ship</td>
            </tr>
        }
    </tbody>
</table>

@*pagination buttons starts here*@

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="ListOfAllStaff" media="get" asp-controller="CPOUpdate"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="ListOfAllStaff" media="get" asp-controller="CPOUpdate"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-default @nextDisabled">
    Next
</a>

NNPEFWEB/Views/CPOUpdate/ListOfCertisfiedForm.cshtml
@model NNPEFWEB.ViewModel.PaginatedList<NNPEFWEB.Models.ef_personalInfo>
@using Microsoft.AspNetCore.Authorization

@{ ViewData["Title"] = "UpdatedPersonelByCPO"; }



<h1 style="margin-top:-20px">Personnel Report List</h1>
<br />
<h4>Filter By: </h4>
<div class="row">
    <div class="col-md-6 mb-4">
        <form asp-action="ListOfCertisfiedForm" method="get" asp-controller="CPOUpdate">
            <div class="row">
                <div class="col-md-4">
                    <label class="control-label">Status</label>
                    <select name="status" class="form-control">
                        @if (ViewData["status"] != null)
                        {

                            @switch (ViewData["status"])
                            {
                                case "AllStaff":
                                    <option selected value="@ViewData["status"]">All</option>
                                    <option value="SHIP">Completed Form</option>
                                    <option value="CPO">Authenticated Form</option>
                                    <option value="Verified">Certified Form</option>
                                    <option value="Processed">Processed Form</option>
                                    break;
                                case "Completed":
                                    <option value="AllStaff">All </option>
                                    <option selected value="@ViewData["status"]">Completed Form</option>
                                    <option value="CPO">Authenticated Form</option>
                                    <option value="Verified">Certified Form</option>
                                    <option value="Processed">Processed Form</option>
                                    break;
                                case "Auth":
                                    <option value="AllStaff">All</option>
                                    <option value="SHIP">Completed Form</option>
                                    <option selected value="@ViewData["status"]">Authenticated Form</option>
                                    <option value="Verified">Certified Form</option>
                                    <option value="Processed">Processed Form</option>
                                    break;
                                case "Verified":
                                    <option value="AllStaff">All</option>
                                    <option value="SHIP">Completed Form</option>
                                    <option value="CPO">Authenticated Form</option>
                                    <option selected value="@ViewData["status"]">Certified Form</option>
                                    <option value="Processed">Processed Form</option>
                                    break;
                                case "Processed":
                                    <option value="AllStaff">All</option>
                                    <option value="SHIP">Completed Form</option>
                                    <option value="CPO">Authenticated Form</option>
                                    <option value="Verified">Certified Form</option>
                                    <option selected value="@ViewData["status"]">Processed Form</option>
                                    break;
                                default:
                                    <option value="AllStaff">All</option>
                                    <option value="SHIP">Completed Form</option>
                                    <option value="CPO">Authenticated Form</option>
                                    <option value="Verified">Certified Form</option>
                                    <option value="Processed">Processed Form</option>
                                    break;
                            }
                        }
                        else
                        {
                            <option value="AllStaff">All</option>
                            <option value="SHIP">Completed Form</option>
                            <option value="CPO">Authenticated Form</option>
                            <option value="Verified">Certified Form</option>
                            <option value="Processed">Processed Form</option>
                        }



                    </select>
                </div>

                <div class="col-md-4">
                    <label class="control-label">Ship</label>
                    <select name="ship"
                            class="form-control"
                            asp-items="@(new SelectList(ViewBag.ShipList,"Value", "Text"))">
                    </select>
                </div>

                <div class="col-md-4" style="margin-top:30px">
                    <input type="submit" class="btn btn-primary" value="Filter" />
                </div>

            </div>
        </form>
    </div>
    <div class="col-md-3 mt-4">
        <form asp-action="ExportByHOD2" method="post" asp-controller="CPOUpdate">

            <input type="hidden" name="status" value="@ViewData["status"]" />

            <input type="hidden" name="ship" value="@ViewData["shipSearchedID"]" />

            <input type="submit" class="btn btn-primary" value="Download To Excel" />

        </form>
    </div>

    <div class="col-md-3 mt-4">
        <form asp-action="ListOfAllStaffReportByHOD" method="get" asp-controller="CPOUpdate">

            <input type="hidden" name="status" value="@ViewData["status"]" />

            <input type="hidden" name="ship" value="@ViewData["shipSearchedID"]" />

            <input type="submit" class="btn btn-primary" value="Download To PDF" />
        </form>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Rank</th>
            <th>Service No</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Ship</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var r in Model)
        {
        <tr>
            <td>@r.Rank</td>
            <td>@r.serviceNumber</td>
            <td>@r.Surname</td>
            <td>@r.OtherName</td>
            <td>@r.ship</td>
            <td>
                @if (r.classes == 1)
                {
                    <a asp-controller="PersonalInfo" asp-action="ViewPersonel" asp-route-svcno="@r.serviceNumber" class="btn btn-success">View Details</a>}
                @if (r.classes == 2)
                {
                    <a asp-controller="PersonalInfo" asp-action="ViewPersonelRating" asp-route-svcno="@r.serviceNumber" class="btn btn-success">View Details</a>}
                @if (r.classes == 3)
                {
                    <a asp-controller="PersonalInfo" asp-action="ViewPersonelTraining" asp-route-svcno="@r.serviceNumber" class="btn btn-success">View Details</a>}
            </td>
        </tr>
        }
    </tbody>
</table>

@*pagination buttons starts here*@

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="ListOfCertisfiedForm" media="get" asp-controller="CPOUpdate"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="ListOfCertisfiedForm" media="get" asp-controller="CPOUpdate"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-default @nextDisabled">
    Next
</a>

NNPEFWEB/Views/CPOUpdate/UpdatedPayroll.cshtml
@{
    ViewData["Title"] = "UpdatedPayroll";
}

<h1>Update Payroll</h1>
 @if (TempData["UpdateMessage"] != null) { 
<h3>@TempData["UpdateMessage"]</h3>
}
<form asp-action="UpdatedPayroll" asp-controller="CPOUpdate">
    <div class="row">
        <div class="col-md-4">
            <select name="payclass" class="form-control">
                <option value="1">OFP</option>
                <option value="2">WOP</option>
                <option value="3">JRPA</option>
                <option value="4">JRPB</option>
                <option value="5">JRPC</option>
                <option value="6">TRNP</option>
                
            </select>
        </div>

        <div class="col-md-4">
            <input type="submit" class="btn btn-primary" value="Update" />
        </div>
    </div>
</form>

NNPEFWEB/Views/CPOUpdate/UpdatedPersonelByCPO.cshtml
@model IEnumerable<NNPEFWEB.Models.ef_personalInfo>
@using Microsoft.AspNetCore.Authorization

@{ ViewData["Title"] = "UpdatedPersonelByCPO"; }



<h1>Personnel  List</h1>

<div class="row">
    <div class="col-md-12">
        <form asp-action="UpdatedPersonelByCPO" method="get" asp-controller="CPOUpdate">
            <div class="row">

                <div class="col-md-3 mt-4">
                    <label class="control-label">Ship</label>

                    <select name="ship"
                            class="form-control"
                            asp-items="@(new SelectList(ViewBag.ShipList,"Value", "Text"))">
                    </select>
                </div>
                <div class="col-md-3 mt-2">
                    <input type="submit" class="btn btn-primary" value="Search" style="margin-top:25px" />
                </div>

            </div>
            
        </form>
            </div>
            <div class="row" style="margin-left:800px;margin-top:-90px">
                <div class="col-md-3 mt-4">
                    <form asp-action="ExportByHOD" method="post" asp-controller="CPOUpdate">

                        <input type="hidden" name="ship" value="@ViewData["shipSearchedID"]" />

                        <input type="submit" class="btn btn-primary" value="Download To Excel" />

                    </form>
                </div>
                
                <div class="col-md-3 mt-4" style="margin-left:60px">
                    <form asp-action="ListOfCompletedForm" method="get" asp-controller="CPOUpdate">

                        <input type="hidden" name="ship" value="@ViewData["shipSearchedID"]" />

                        <input type="submit" class="btn btn-primary" value="Download To PDF" />
                    </form>
                </div>
            </div>

        </div>
    
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Rank</th>
            <th>Service No</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Ship</th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var r in Model)
        {
<tr>
    <td>@r.Rank</td>
    <td>@r.serviceNumber</td>
    <td>@r.Surname</td>
    <td>@r.OtherName</td>
    <td>@r.ship</td>
    <td>
        @if (r.classes == 1)
        {
         <a asp-controller="CPOUpdate" asp-action="UpdatedPayroll" asp-route-id="@r.Id" class="btn btn-success">ACCEPT</a>
         <a asp-controller="PersonalInfo" asp-action="ViewPersonel" asp-route-svcno="@r.serviceNumber" class="btn btn-success" target="_blank">View Details</a>
         @*<a asp-controller="Command" asp-action="downloadFormOfficer" asp-route-svcno="@r.serviceNumber" class="btn btn-dark" target="_blank">Print Page 1</a>
         <a asp-controller="Command" asp-action="downloadFormOfficer2" asp-route-svcno="@r.serviceNumber" class="btn btn-dark" target="_blank">Print Page 2</a>*@
             
             }
        @if (r.classes == 2)
        {
          <a asp-controller="CPOUpdate" asp-action="UpdatedPayroll" asp-route-id="@r.Id" class="btn btn-success">ACCEPT</a>
          <a asp-controller="PersonalInfo" asp-action="ViewPersonel" asp-route-svcno="@r.serviceNumber" class="btn btn-success" target="_blank">View Details</a>
          @*<a asp-controller="Command" asp-action="downloadForm" asp-route-svcno="@r.serviceNumber" class="btn btn-dark" target="_blank">Print Page 1</a>
          <a asp-controller="Command" asp-action="downloadForm2" asp-route-svcno="@r.serviceNumber" class="btn btn-dark" target="_blank">Print Page 2</a>*@
          }
        @if (r.classes == 3)
        {
        <a asp-controller="CPOUpdate" asp-action="UpdatedPayroll" asp-route-id="@r.Id" class="btn btn-success">ACCEPT</a>
        <a asp-controller="PersonalInfo" asp-action="ViewPersonel" asp-route-svcno="@r.serviceNumber" class="btn btn-success" target="_blank">View Details</a>
        @*<a asp-controller="Command" asp-action="downloadFormTraining" asp-route-svcno="@r.serviceNumber" class="btn btn-dark" target="_blank">Print Page 1</a>
        <a asp-controller="Command" asp-action="downloadFormTraining2" asp-route-svcno="@r.serviceNumber" class="btn btn-dark" target="_blank">Print Page 2</a>*@
        }
    </td>


</tr>}
    </tbody>
</table>