NNPEFWEB/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using NNPEFWEB.Data;
using NNPEFWEB.Models;
using NNPEFWEB.Service;
using NNPEFWEB.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;

namespace NNPEFWEB.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly IContactUsService _contactUsService;
        private readonly IConfiguration config;
        private readonly IPersonInfoService personinfoService;
        private readonly ApplicationDbContext _context;
        public ContactUsController(IPersonInfoService _personinfoService,IContactUsService contactUsService, IConfiguration configuration, ApplicationDbContext _context)
        {
            this._contactUsService = contactUsService;
            config = configuration;
            this._context = _context;
            personinfoService = _personinfoService;
        }

        // GET: ContactUsController
        [HttpGet]
        public IActionResult Index()
        {
            var cons = _contactUsService.GetListContacts();
            //var contactus = _context.ef_contactUs.Where(x => x.Response == null).ToList();
            //var contactList = _contactUsService.GetContacts().Where(x=>x.Response==null);

            //List<ContactUsViewModel> contactUsViewModel = new List<ContactUsViewModel>();

            //foreach (var contact in contactList)
            //{
            //    var contactUsVM = new ContactUsViewModel
            //    {
            //        Id = contact.Id,
            //        PersonName = contact.PersonName,
            //        Ship = contact.Ship,
            //        Email = contact.Email,
            //        PhoneNumber = contact.PhoneNumber,
            //        Message = contact.Message,
            //        Response = contact.Response
            //    };

            //    contactUsViewModel.Add(contactUsVM);
            //}

            return View(cons);
        }

        // GET: ContactUsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContactUsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactUsController/Create
        [HttpPost]
        public IActionResult Create(ContactUsViewModel contactsVM)
        {
            try
            {
                var per = personinfoService.GetPersonalInfo(contactsVM.PersonName).Result;
                if (ModelState.IsValid)
                {
                    if (per == null)
                    {
                        TempData["Message"] = "Maybe you are not a personeel, please contact the admin directly or use the live chat";
                        return RedirectToAction("homepage", "Home");
                    }
                    var newContact = new ef_ContactUs
                    {
                        PersonName = contactsVM.PersonName,
                        Ship = contactsVM.Ship,
                        Email = contactsVM.Email,
                        PhoneNumber = contactsVM.PhoneNumber,
                        Message = contactsVM.Message
                    };

                    var createdContact = _contactUsService.CreateContact(newContact).Result;

                    if (createdContact == true)
                    {
                        TempData["Message"] = "Ticket Successfully Summitted!!!";
                    }
                    else
                    {
                        TempData["Message"] = "Error occured while trying to Create Contact!!!";
                    }
                }
                return RedirectToAction("homepage","Home");
            }
            catch(Exception ex)
            {
                TempData["Message"] = ex.Message;
                return RedirectToAction("homepage", "Home");
            }
        }

        // GET: ContactUsController/Edit/5
        public ActionResult Edit(int id)
        {
            ContactUsViewModel contactUsViewModel = new ContactUsViewModel();
            try
            {
                var contactInDB = _contactUsService.GetContactById(id);

                if (contactInDB != null)
                {
                    contactUsViewModel.Id = contactInDB.Id;
                    contactUsViewModel.PersonName = contactInDB.PersonName;
                    contactUsViewModel.Ship = contactInDB.Ship;
                    contactUsViewModel.Email = contactInDB.Email;
                    contactUsViewModel.PhoneNumber = contactInDB.PhoneNumber;
                    contactUsViewModel.Message = contactInDB.Message;
                    contactUsViewModel.Response = contactInDB.Response;

                    return View(contactUsViewModel);
                }
                else
                {
                    TempData["Message"] = "Contact doesn't exist!!";
                }
            }
            catch (Exception ex)
            {

                TempData["Message"] = ex.Message;
            }
            return View(contactUsViewModel);
        }

        // POST: ContactUsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContactUsViewModel contactsVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newContact = new ef_ContactUs
                    {
                        Id = contactsVM.Id,
                        PersonName = contactsVM.PersonName,
                        Ship = contactsVM.Ship,
                        Email = contactsVM.Email,
                        PhoneNumber = contactsVM.PhoneNumber,
                        Message = contactsVM.Message,
                        Response = contactsVM.Response
                    };
                    string emailFrom = "NN-CPO";
                    string emailSender = config.GetValue<string>("mailconfig:SenderEmail");
                    if (!string.IsNullOrEmpty(contactsVM.Email))
                        SendEmailNotification(emailFrom, emailSender, contactsVM.Response+" To Your "+contactsVM.Message , contactsVM.Email);

                    var response = _contactUsService.UpdateContactInfo(newContact).Result;

                    TempData["Message"] = response;
                }
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                TempData["Message"] = ex.Message;
                return View(contactsVM);
            }
        }
        public void SendEmailNotification(string emailFrom, string sender, string messageToSend, string receipient)
        {

            var UserName = config.GetValue<string>("mailconfig:SenderEmail");
            var Password = config.GetValue<string>("mailconfig:Password");
            var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress(receipient));
            message.From = new MailAddress(sender, emailFrom);
            message.Subject = "Password Verification Code";
            message.Body = string.Format(body, emailFrom, sender, messageToSend);
            message.IsBodyHtml = true;



            string host = config.GetValue<string>("mailconfig:Server");
            int port = config.GetValue<int>("mailconfig:Port");
            var enableSSL = config.GetValue<bool>("mailconfig:enableSSL");

            SmtpClient SmtpServer = new SmtpClient(host);

            var smtp = new SmtpClient
            {
                Host = host,
                Port = port,
                EnableSsl = enableSSL,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = true,
                Credentials = new NetworkCredential(UserName, Password)
            };
            SmtpServer.Port = port; // Also Add the port number to send it, its default for Gmail
            SmtpServer.Credentials = new System.Net.NetworkCredential(UserName, Password);
            SmtpServer.EnableSsl = enableSSL;
            SmtpServer.Timeout = 200000; // Add Timeout property
            SmtpServer.Send(message);


        }
        // GET: ContactUsController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var contactInDb = _contactUsService.GetContactById(id);

                if (contactInDb != null)
                {
                    var response = _contactUsService.DeleteContactById(contactInDb.Id).Result;

                    if (response == true)
                        TempData["Message"] = "Contact Deleted Successfully!!! ";
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;

                return RedirectToAction(nameof(Index));
            }
        }

        // POST: ContactUsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NNPEFWEB/Views/ContactUs/Create.cshtml
@using NNPEFWEB.ViewModel
@model ContactUsViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_CustomLayout.cshtml"; 
}

@*<style>

    body {
        opacity: 0;
    }
</style>
<style>

    .caption {
        display: flex;
        flex-direction: column;
    }

    .user {
        display: flex;
        flex-direction: row;
    }
</style>
<style>
    .e-row:hover {
        cursor: pointer;
        background-color: #03a9f430 !important
    }
</style>*@

    <!--<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-6">
                    <div class="card2 card border-0 px-4 py-5">-->
                        @*<div class="row mb-4 px-3">
                                <h3>Sign in Here</h3>


                            </div>*@

                        <!--<div class="row px-3 mb-4">
                            <div class="line"></div>
                            <div class="line"></div>
                        </div>-->


                        @if (TempData["Message"] != null)
                        {
                            <div class="alert alert-success" role="alert">
                                @TempData["Message"]
                            </div>
                        }

                        <div class="page-wrapper">

                            @using (Html.BeginForm("Create", "ContactUs", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <div class="section-heading">
                                                <h1 class="page-title">Add Contacts</h1>
                                            </div>
                                            <button type="button" class="close dismiss-modal" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">

                                            <span style="font-weight:bold; ">Contact Details</span>
                                            <hr />
                                            <div class="row">
                                                <div class="form-group col-sm-6">
                                                    <label class="control-label">
                                                        Person Name
                                                    </label>
                                                    @Html.TextBoxFor(model => model.PersonName, new { @class = "form-control" })
                                                </div>
                                                <div class="form-group col-sm-6">
                                                    <label class="control-label">
                                                        Ship
                                                    </label>
                                                    @Html.TextBoxFor(model => model.Ship, new { @class = "form-control" })
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="form-group col-sm-6">
                                                    <label for="email" class="control-label">
                                                        Email
                                                    </label>
                                                    @Html.TextBoxFor(model => model.Email, new { @type = "email", @class = "form-control" })
                                                </div>

                                                <div class="form-group col-sm-6">
                                                    <label class="control-label">
                                                        Phone Number
                                                    </label>
                                                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-sm-6">
                                                    <label class="control-label">
                                                        Message
                                                    </label>
                                                    @Html.TextAreaFor(model => model.Message, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <br />

                                            <div class="modal-footer">
                                                <button type="reset" class="btn btn-secondary ">Cancel</button>
                                                <button type="submit" value="save" name="save" class="btn btn-success">Save</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    @*</div>
                </div>
            </div>*@
            <div class="bg-blue py-4">
                <div class="row px-3">
                    <small class="ml-4 ml-sm-5 mb-2">
                        Copyright &copy; @DateTime.Now.Year<a style="color:yellowgreen" href="https://hicadsystemsltd.com/" _blank>Hicad Systems LTD</a> All rights
                        reserved.
                    </small>

                </div>
            </div>
        @*</div>
    </div>*@

NNPEFWEB/Views/ContactUs/Edit.cshtml
@using NNPEFWEB.ViewModel
@model ContactUsViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

    body {
        opacity: 0;
    }
</style>
<style>

    .caption {
        display: flex;
        flex-direction: column;
    }

    .user {
        display: flex;
        flex-direction: row;
    }
</style>
<style>
    .e-row:hover {
        cursor: pointer;
        background-color: #03a9f430 !important
    }
</style>

@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<div class="page-wrapper">

    @using (Html.BeginForm("Edit", "ContactUs", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="section-heading">
                        <h1 class="page-title">Respond To Ticket</h1>
                    </div>
                    <button type="button" class="close dismiss-modal" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    @Html.HiddenFor(model => model.Id)
                    <span style="font-weight:bold; ">Ticket Details</span>
                    <hr />
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label class="control-label">
                                 Name
                            </label>
                            @Html.TextBoxFor(model => model.PersonName, new { @class = "form-control", @readonly = "true" })
                        </div>
                        <div class="form-group col-sm-6">
                            <label class="control-label">
                                Ship
                            </label>
                            @Html.TextBoxFor(model => model.Ship, new { @class = "form-control" , @readonly = "true" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="email" class="control-label">
                                Email
                            </label>
                            @Html.TextBoxFor(model => model.Email, new { @type = "email", @class = "form-control", @readonly = "true" })
                        </div>

                        <div class="form-group col-sm-6">
                            <label class="control-label">
                                Phone Number
                            </label>
                            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label class="control-label">
                                Message
                            </label>
                            @Html.TextAreaFor(model => model.Message, new { @class = "form-control", @readonly = "true" })
                        </div>
                        <div class="form-group col-sm-6">
                            <label class="control-label">
                                Response
                            </label>
                            @Html.TextAreaFor(model => model.Response, new { @class = "form-control" })
                        </div>
                    </div>
                    <br />

                    <div class="modal-footer">
                        <button type="reset" class="btn btn-secondary ">Cancel</button>
                        <button type="submit" value="save" name="save" class="btn btn-success">Update</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

NNPEFWEB/Views/ContactUs/Index.cshtml
@model IEnumerable<NNPEFWEB.Models.ef_ContactUs>

@{
    ViewData["Title"] = "Contact";
  //  Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<style>

    body {
        opacity: 0;
    }
</style>
<style>

    .caption {
        display: flex;
        flex-direction: column;
    }

    .user {
        display: flex;
        flex-direction: row;
    }
</style>
<style>
    .e-row:hover {
        cursor: pointer;
        background-color: #03a9f430 !important
    }
</style>*@

@if (TempData["Message"] != null)
{
<div class="alert alert-success" role="alert">
    @TempData["Message"]
</div>
}


<div class="page-wrapper">
    <div class="container-fluid">
        <div class="section-heading">
            <h1 class="page-title">View Ticket</h1>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-3">
                    @*<button class='btn btn-success btn-block'>
                        <i class="fa fa-plus"></i> &nbsp; @Html.ActionLink("Create Contact", "Create", "ContactUs", null, new { style = "color: white;" })
                    </button>*@
                </div>
                <hr class="btn-block">
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table @*id="data-table-user"*@ class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <td>Person Name</td>
                                <td>Ship</td>
                                <td>Email Address</td>
                                <td>Phone Number</td>
                                <td>Message</td>
                                <td>Response</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var contact in Model)
                            {
                                <tr>
                                    <td>@contact.PersonName</td>
                                    <td>@contact.Ship</td>
                                    <td>@contact.Email</td>
                                    <td>@contact.PhoneNumber</td>
                                    <td>@contact.Message</td>
                                    <td>@contact.Response</td>
                                    <td>
                                        @Html.ActionLink("Response", "Edit", "ContactUs", new { Id = contact.Id }, new { @class = "btn btn-primary" })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Remove", "Delete", "ContactUs", new { Id = contact.Id }, new { @class = "btn btn-danger" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>