NNPEFWEB/Controllers/StaticTablesController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NNPEFWEB.Data;
using NNPEFWEB.Models;

namespace NNPEFWEB.Controllers
{
    public class StaticTablesController : Controller
    {
        private readonly ApplicationDbContext _context;
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        SqlConnection con = new SqlConnection();
        List<ef_ship> addresses = new List<ef_ship>();
        private readonly ILogger<HomeController> _logger;
        private readonly string connectionString;
        public StaticTablesController(ApplicationDbContext _context, ILogger<HomeController> logger, IConfiguration configuration)
        {
            this._context = _context;
            _logger = logger;
            con.ConnectionString = configuration.GetConnectionString("DefaultConnection");
        }
        public IActionResult Index2()
        {
            FetchData();
            return View(addresses);
        }
        private void FetchData()
        {
            if (addresses.Count > 0)
            {
                addresses.Clear();
            }
            try
            {
                con.Open();
                com.Connection = con;
                com.CommandText = "SELECT TOP (1000) [Id],[shipName],[code] from ef_ships";
                dr = com.ExecuteReader();
                while (dr.Read())
                {
                    addresses.Add(new ef_ship()
                    {
                        Id=Convert.ToInt32(dr["Id"]),
                        shipName = dr["shipName"].ToString()
                    ,
                        code = dr["code"].ToString()
                    });;
                }
                con.Close();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public IActionResult Index()
        {
            var ship= _context.ef_ships.ToList();
            return View(ship);
        }
        public IActionResult createship()
        {
           ViewBag.GetCommands=GetCommand();
            return View();
        }
        [HttpPost]
        public IActionResult createship(ef_ship ships)
        {
            try
            {

            if (ships != null)
            {
                var checkship = _context.ef_ships.Where(x => x.shipName == ships.shipName).Count();
                if (checkship == 0)
                {
                    _context.ef_ships.Add(ships);
                    _context.SaveChanges();

                    return RedirectToAction(nameof(Index2));
                }
            }
                else
                {
                    TempData["messages"] = "Ship already Exist";
                    return RedirectToAction(nameof(createship));
                }

               
            return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                TempData["messages"] = "Error Contact Admin";
                return RedirectToAction(nameof(Index));
            }
        }
        public IActionResult Editship(int id)
        {
            ViewBag.GetCommands = GetCommand();
            var ships = _context.ef_ships.Where(x => x.Id == id).FirstOrDefault();
            var rec = new ef_ship
            {
                Id=ships.Id,
                shipName = ships.shipName,
                code = ships.code,
                commandid = ships.commandid
            };
            return View(rec);
        }
        [HttpPost]
        public IActionResult Editship(ef_ship ships)
        {
            try
            {

                if (ships != null)
                {
                    var checkship = _context.ef_ships.Where(x => x.Id == ships.Id).Count();
                    if (checkship != 0)
                    {
                        _context.ef_ships.Update(ships);
                        _context.SaveChanges();

                        return RedirectToAction(nameof(Index2));
                    }
                }
                

                return RedirectToAction(nameof(Index2));

            }
            catch (Exception ex)
            {
                TempData["messages"] = "Error Contact Admin";
                return RedirectToAction(nameof(Index));
            }
        }
        public IActionResult Deleteship(int id)
        {
            var ships = _context.ef_ships.Where(x => x.Id == id).FirstOrDefault();
            _context.ef_ships.Remove(ships);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index2));
        }

        public List<SelectListItem> GetCommand()
        {
            var commandList = (from rk in _context.ef_commands
                               select new SelectListItem()
                               {
                                   Text = rk.commandName,
                                   Value = rk.code.ToString(),
                               }).ToList();

            commandList.Insert(0, new SelectListItem()
            {
                Text = "Select Command",
                Value = string.Empty
            });
            return commandList;
        }
    }
}

NNPEFWEB/Views/StaticTables/Editship.cshtml
@model NNPEFWEB.Models.ef_ship
@{
    ViewData["Title"] = "createship";
}

<h1>Edit Ship</h1>
<form asp-action="Editship" method="post" asp-controller="StaticTables">
    <div class="row">
        <div class="col-md-4">
            <label>Ship Name</label>
            <input type="text" asp-for="shipName" class="form-control" />
        </div>
        <div class="col-md-4">
            <label>Command</label>
            <select asp-for="code"
                    class="form-control"
                    asp-items="@(new SelectList(ViewBag.GetCommands,"Value", "Text"))">
            </select>
           @* @Html.DropDownList("code", new SelectList(ViewBag.commands, "Value", "Text"), new { @class = "form-control" })*@
        </div>

    </div>
    <br />
    <div class="row">
        <div class="col-md-4">
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
    </div>

</form>

NNPEFWEB/Views/StaticTables/Index.cshtml
@model IEnumerable<NNPEFWEB.Models.ef_ship>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<a asp-action="createship" class="btn btn-success">Add</a>
<table class="table-active">
    <thead>
        <tr>
            <th>Ship Name</th>
            <th>Command</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            @foreach(var r in Model)
            {
            <td>@r.shipName</td>
            <td>@r.code</td>
            <td>
                <a asp-action="Editship"  asp-controller="StaticTables" asp-route-id="@r.Id" class="btn btn-success">Edit</a>
                <a asp-action="Deleteship" asp-controller="StaticTables" asp-route-id="@r.Id" class="btn btn-danger">Delete</a>
            </td>
            }
            
        </tr>
    </tbody>
</table>

NNPEFWEB/Views/StaticTables/Index2.cshtml
@{ ViewData["Title"] = "SHIP";
                string[] TableHeaders = new string[] {"Ship Name"
                        ,"Command"
                        ,"Action"
                        }; }

<a asp-action="createship" class="btn btn-success">Add</a>
<div class="table">
    <table id="myTable" class="table table-md">
        <thead>
            <tr>
                @{ foreach (var head in TableHeaders)
                                {
                    <th>
                        @head
                    </th> } }
            </tr>
        </thead>

        <tbody>
            @{ if (Model != null)
                            {
                                foreach (var Data in Model)
                                {
                <tr>
                    <td>@Data.shipName</td>
                    <td>@Data.code</td>
                    <td>
                        <a asp-action="Editship" asp-controller="StaticTables" asp-route-id="@Data.Id" class="btn btn-success">Edit</a>
                        <a asp-action="Deleteship" asp-controller="StaticTables" asp-route-id="@Data.Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr> }
                            } }
        </tbody>
    </table>
</div>

NNPEFWEB/Views/StaticTables/createship.cshtml
@model NNPEFWEB.Models.ef_ship
@{
    ViewData["Title"] = "createship";
}

<h1>createship</h1>
<form asp-action="createship" method="post" asp-controller="StaticTables">
    <div class="row">
        <div class="col-md-4">
            <label>Ship Name</label>
            <input type="text" asp-for="shipName" class="form-control" />
        </div>
        <div class="col-md-4">
            <label>Command</label>
            @Html.DropDownList("code", new SelectList(ViewBag.GetCommands, "Value", "Text"), new { @class = "form-control" })
        </div>

    </div>
   <br />
    <div class="row">
        <div class="col-md-4">
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
    </div>

</form>